// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArckU8G1FL6f9wJaEgz-CX5FXFmJ-m22I',
    appId: '1:470185874797:web:c91017595f05d8fadcb664',
    messagingSenderId: '470185874797',
    projectId: 'at-91-e17f7',
    authDomain: 'at-91-e17f7.firebaseapp.com',
    storageBucket: 'at-91-e17f7.firebasestorage.app',
    measurementId: 'G-QWLRW6SWJF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNGramz-UobDPK8KIDqLGAxszGmQ8N6aI',
    appId: '1:470185874797:android:50aab4931ad04823dcb664',
    messagingSenderId: '470185874797',
    projectId: 'at-91-e17f7',
    storageBucket: 'at-91-e17f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5cn7FZzYUKA-dfsJvHXC6Fe7idEDn35w',
    appId: '1:470185874797:ios:045d1d1f06b85fe8dcb664',
    messagingSenderId: '470185874797',
    projectId: 'at-91-e17f7',
    storageBucket: 'at-91-e17f7.firebasestorage.app',
    iosBundleId: 'com.example.at91f',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5cn7FZzYUKA-dfsJvHXC6Fe7idEDn35w',
    appId: '1:470185874797:ios:045d1d1f06b85fe8dcb664',
    messagingSenderId: '470185874797',
    projectId: 'at-91-e17f7',
    storageBucket: 'at-91-e17f7.firebasestorage.app',
    iosBundleId: 'com.example.at91f',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArckU8G1FL6f9wJaEgz-CX5FXFmJ-m22I',
    appId: '1:470185874797:web:3d7bc5fdcee67719dcb664',
    messagingSenderId: '470185874797',
    projectId: 'at-91-e17f7',
    authDomain: 'at-91-e17f7.firebaseapp.com',
    storageBucket: 'at-91-e17f7.firebasestorage.app',
    measurementId: 'G-7HY6PSP7RH',
  );
}
